name: Generate 3D Contribution Graph

on:
  schedule: # runs every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # lets you run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate 3D profile contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          USERNAME: ShamirAli55

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
