name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight
  workflow_dispatch:       # allow manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          user_name: ShamirAli55   # 👈 your username here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
